CREATE TABLE baskets(
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `shipped` BOOLEAN NOT NULL DEFAULT FALSE,
  `totalPrice` FLOAT NOT NULL DEFAULT 0,
  `userId` INT NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES users (id)
)