CREATE TABLE orders(
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `orderPrice` FLOAT NOT NULL DEFAULT 0,
  `quantity` INT NOT NULL DEFAULT 0,
  `basketId` INT NOT NULL,
  `productId` INT NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_basket_id FOREIGN KEY (basketId) REFERENCES baskets (id),
  CONSTRAINT fk_product_id FOREIGN KEY (productId) REFERENCES products (id)
)