CREATE TABLE products(
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(31) NOT NULL,
  `unitPrice` FLOAT NOT NULL DEFAULT 0,
  `unitsOnStock` INT NOT NULL DEFAULT 0,
  `categoryId` INT DEFAULT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_category FOREIGN KEY (categoryId) REFERENCES categories (id)
)