CREATE TABLE users(
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(31) NOT NULL,
  `username` VARCHAR(31) NOT NULL,
  `password` VARCHAR (63) NOT NULL,
  `cash` FLOAT NOT NULL DEFAULT 0,
  `roleId` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_role FOREIGN KEY (roleId) REFERENCES roles (id)
)